spring:
  flyway.locations: classpath:db/migration

  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:dbjuddata
    username: ${POSTGRES_USERNAME:dbjuddata}
    password: ${POSTGRES_PASSWORD:dbjuddata}

security:

  authorisedServices:
    - "it"